const GAMES = [
  { id: 1,  name: "Cyberpunk 2077",        genre: "RPG · Ação",           price: 149.90, rating: 9.2, cover: "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/library_600x900.jpg",   badge: "sale",  featured: true,  bestseller: false },
  { id: 2,  name: "Elden Ring",            genre: "RPG · Souls",           price: 199.90, rating: 9.8, cover: "https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/library_600x900.jpg",   badge: "new",   featured: true,  bestseller: true  },
  { id: 3,  name: "GTA VI",               genre: "Ação · Mundo Aberto",   price: 299.90, rating: 9.5, cover: GTA6_COVER, badge: "new",   featured: true,  bestseller: true  },
  { id: 4,  name: "Red Dead Redemption 2", genre: "Ação · Aventura",       price: 99.90,  rating: 9.7, cover: "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/library_600x900.jpg",   badge: null,    featured: false, bestseller: true  },
  { id: 5,  name: "The Witcher 3",         genre: "RPG",                   price: 79.90,  rating: 9.6, cover: "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/library_600x900.jpg",    badge: "sale",  featured: false, bestseller: true  },
  { id: 6,  name: "Hades II",             genre: "Roguelike · Ação",      price: 59.90,  rating: 9.1, cover: "https://cdn.cloudflare.steamstatic.com/steam/apps/1145360/library_600x900.jpg",   badge: "new",   featured: true,  bestseller: false },
  { id: 7,  name: "Hollow Knight",         genre: "Metroidvania",          price: 39.90,  rating: 9.3, cover: "https://cdn.cloudflare.steamstatic.com/steam/apps/367520/library_600x900.jpg",    badge: null,    featured: false, bestseller: true  },
  { id: 8,  name: "Baldur's Gate 3",       genre: "RPG · Estratégia",     price: 249.90, rating: 9.9, cover: "https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/library_600x900.jpg",   badge: null,    featured: true,  bestseller: true  },
  { id: 9,  name: "Sekiro",               genre: "Ação · Souls",          price: 149.90, rating: 9.4, cover: "https://cdn.cloudflare.steamstatic.com/steam/apps/814380/library_600x900.jpg",    badge: "sale",  featured: false, bestseller: false },
  { id: 10, name: "Dead Space Remake",     genre: "Terror · Ação",        price: 179.90, rating: 8.8, cover: "https://cdn.cloudflare.steamstatic.com/steam/apps/1693980/library_600x900.jpg",   badge: null,    featured: false, bestseller: false },
  { id: 11, name: "Starfield",            genre: "RPG · Exploração",      price: 199.90, rating: 7.8, cover: "https://cdn.cloudflare.steamstatic.com/steam/apps/1716740/library_600x900.jpg",   badge: "sale",  featured: false, bestseller: false },
  { id: 12, name: "Forza Horizon 5",       genre: "Corrida",               price: 159.90, rating: 9.0, cover: "https://cdn.cloudflare.steamstatic.com/steam/apps/1551360/library_600x900.jpg",   badge: null,    featured: false, bestseller: true  },
];
